apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3lng
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3lng
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3lng
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3lng
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3lng
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-selx-tenant/rhtap-demo-app/hacbs-test-project-3lng@sha256:c9e771834c8fd815c553c11a8f0616cbe80fbce96b22ffd4af247a9438c47856
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
