apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3lng
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-selx-tenant/rhtap-demo-app/hacbs-test-project-3lng@sha256:40bf8c8857272291922b39458338f6617f8c81b4e0c2a2cde8bfd352e7850506
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
