apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3lng
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-selx-tenant/rhtap-demo-app/hacbs-test-project-3lng@sha256:c9e771834c8fd815c553c11a8f0616cbe80fbce96b22ffd4af247a9438c47856
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
